name: Lint

on:
  workflow_run:
    workflows: ["Black Formatter"]
    branches: ["main"]
    types: 
      - completed
  
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make lint
